from project.controller import Controller

controller = Controller()
print(controller.add_aquarium('FreshwaterAquarium', 'Aquarium'))
print(controller.add_aquarium('SaltwaterAquarium', 'Aquarium2'))
print(controller.add_aquarium('SaltwaterAquarium', 'Aquarium3'))
print(controller.add_decoration('Plant'))
print(controller.add_decoration('Ornament'))
print(controller.add_decoration('Ornamenta'))
print(controller.insert_decoration('Aquarium', 'Plant'))
print(controller.insert_decoration('Aquarium', 'Ornament'))
print(controller.insert_decoration('Aquarium', 'Ornamentt'))
print(controller.add_fish('Aquarium', 'FreshwaterFish', 'Nemo', 'species', 2.6))
print(controller.add_fish('Aquarium', 'FreshwaterFish', 'Nemo2', 'species', 2.6))
print(controller.add_fish('Aquarium', 'FreshwaterFish', 'Nemo3', 'species', 2.6))
print(controller.add_fish('Aquarium', 'FreshwaterFish', 'Nemo3', 'species', 2.6))
print(controller.add_fish('Aquarium2', 'SaltwaterFish', 'Nemo3', 'species', 2.6))
print(controller.calculate_value('Aquarium'))
print(controller.report())
print(controller.feed_fish('Aquarium2'))
print(controller.feed_fish('Aquarium'))
print(controller.decorations_repository.decorations)